/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package utilities.views;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import app.Views;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author ducmi
 */
public class NormalFrame extends JFrame {
    JPanel panel;

    /**
     * Creates new form NewJFrame
     */
    public NormalFrame(JPanel panel) {
        this.panel = panel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        getContentPane().setLayout(new AbsoluteLayout());

        getContentPane().add(panel, new AbsoluteConstraints(0, 0, -1, -1));

        setResizable(false);
        pack();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                Views.changeFrame("menu");
            }
        });
    }

    @SuppressWarnings("rawtypes")
    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        if (b && panel instanceof Template)
            ((Template) panel).resetState();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NormalFrame(null).setVisible(true);
            }
        });
    }
}
