/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package utilities.views;

import java.util.Map;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.WindowConstants;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import static java.util.Map.entry;
import views.*;

import javax.swing.JFrame;

/**
 *
 * @author ducmi
 */
public class TabFrame extends JFrame {

    /**
     * Creates new form AA
     */
    public TabFrame(Map<String, JPanel> params) {
        initComponents(params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents(Map<String, JPanel> params) {
        tabs = new JTabbedPane();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new AbsoluteLayout());
        for (Map.Entry<String, JPanel> entry : params.entrySet())
            tabs.addTab(entry.getKey(), entry.getValue());

        getContentPane().add(tabs, new AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabFrame(Map.ofEntries()).setVisible(true);
            }
        });
    }

    private JTabbedPane tabs;
}
